TAL50 Swap logo for dark mode
huuduy216/Talkie-Web pull request #19
Opened 2020-11-19 14:17 UTC by quangthangnho

2020-11-19 14:18 UTC, dnguyen2111 commented on less/forum.less
> +		background-image: url("../../public/background/logo_darkmode.png")!important;
`/background/logo_darkmode.png `thoi nha

2020-11-19 14:19 UTC, dnguyen2111 requested changes

2020-11-19 14:19 UTC, dnguyen2111 commented on .gitignore
xóa bớt 1 dòng, có 2 dòng trống

2020-11-19 14:30 UTC, quangthangnho commented on less/forum.less
> +		background-image: url("../../public/background/logo_darkmode.png")!important;
Em update r nha anh.

2020-11-19 14:31 UTC, quangthangnho commented on .gitignore
Em update r nha a.

2020-11-19 21:11 UTC, huuduy216 approved these changes
Chuẩn

2020-11-19 21:25 UTC, huuduy216 commented
@quangthangnho  don't forget to attach an image or video of the result for reference
![image](https://user-images.githubusercontent.com/10777843/99725930-d3f40880-2a83-11eb-9d62-9f6a77633ba0.png)

2020-11-20 06:37 UTC, PhuTan-Le reviewed
File forum.less có thể đổi url lại thành /public/assets/logo_darkmode.png để hiển thị
Dark mode của trang quản trị chưa đổi được sang logo mới

2020-11-24 23:20 UTC, dnguyen2111 approved these changes

2020-11-26 03:14 UTC, dnguyen2111 approved these changes

2020-11-26 03:14 UTC, merged