TAL38 One button to delete all current drafts
huuduy216/Talkie-Web pull request #55
Opened 2020-12-23 03:09 UTC by quangthangnho

2020-12-23 03:18 UTC, quangthangnho commented
https://user-images.githubusercontent.com/51877144/102955306-29e72080-4508-11eb-8618-74cb2608f777.mp4

Video test!

2020-12-25 11:51 UTC, quangthangnho commented
https://user-images.githubusercontent.com/51877144/103134192-1ee7e800-46e2-11eb-94d0-7308b0dbbf0c.mp4

Update video test

2020-12-26 13:36 UTC, PhuTan-Le submitted a review, later dismissed
Đã test

2020-12-26 16:24 UTC, dnguyen2111 requested changes
Tất cả file trong folder dist không commit (folder này được hệ thống build)

2020-12-26 16:24 UTC, dnguyen2111 commented on vendor/fof/drafts/resources/locale/en.yml
> +      alert_vi: Bạn có chắc muốn xóa tất cả các bản nháp của mình không?
Đặt tên khác hợp lý hơn và dùng tiếng Anh

2020-12-26 16:24 UTC, dnguyen2111 commented on vendor/fof/drafts/resources/locale/en.yml
> +      delete_button1: Xóa tất cả bản nháp
Đặt tên khác hợp lý hơn và dùng tiếng Anh

2020-12-27 15:06 UTC, closed without merging

2020-12-30 07:59 UTC, PhuTan-Le commented
https://user-images.githubusercontent.com/56894648/103338005-94233680-4aaf-11eb-9d47-f47b10bda2cd.mp4

Đã test